### ISSUE TITLE
I have 2 erros

### ISSUE THREAD

**Issue by wild-run** [roleoroleo/yi-hack-Allwinner-v2#311]
1º  Failed to get status of device 192*******
Logger: custom_components.yi_hack.common
Source: custom_components/yi_hack/common.py:188
Integration: Yi Home Cameras with yi-hack (documentation)
First occurred: 22:47:42 (1 occurrences)
Last logged: 22:47:42

Failed to get status of device 192.*********

2º error device update

Logger: homeassistant.components.switch
Source: custom_components/yi_hack/common.py:196
Integration: Interruptor (documentation, issues)
First occurred: 22:47:42 (1 occurrences)
Last logged: 22:47:42

yi_hack: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 633, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/yi_hack/switch.py", line 46, in update
    self._state = get_privacy(self.hass, self._device_name, conf)
  File "/config/custom_components/yi_hack/common.py", line 196, in get_privacy
    privacy_dict: dict = response.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by roleoroleo** [comment]
The integration cannot communicate with the camera or the response is not correct.
1. Check the network connection.
2. Update the cam to the latest hack version.
